Sistema_Evaluacion/Sistema_Evaluacion/Models/Professors.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Evaluacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professors : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professors()
        {
            this.Session = new HashSet<Session>();
        }
    
        public string Name { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Identification { get; set; }
        public string TelephoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string CountryOfBirth { get; set; }
        public byte[] Photo { get; set; }
        public int ProfessorCod { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Assigned { get; set; }
        public string Accesos { get; set; }
        public int UserType { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
    }
}

Sistema_Evaluacion/Sistema_Evaluacion/Controllers/ProfessorController.cs
using Sistema_Evaluacion.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Sistema_Evaluacion.Controllers
{
    public class ProfessorController : Controller
    {
        SistemaEvaluacionEntities sistemaEvaluacionEntities;
        Util util;

        public ProfessorController()
        {
            util = new Util();
            sistemaEvaluacionEntities = new SistemaEvaluacionEntities();
        }

        // GET: Professor
        public ActionResult Create()
        {
            if (Session["usuario"] != null)
            {
                return View();
            }
            else
            {
                return Redirect("/Login");
            }
        }

        public ActionResult ViewAll()
        {
            if (Session["usuario"] != null)
            {
                return View();
            }
            else
            {
                return Redirect("/Login");
            }
        }

        public ActionResult ViewProfile()
        {
            if (Session["usuario"] != null)
            {
                return View();
            }
            else
            {
                return Redirect("/Login");
            }
        }

        [HttpPost]
        public string CreateProfessor(Professors professor)
        {
            var existingProfessor = sistemaEvaluacionEntities.Professors.Where(c => c.ProfessorCod == professor.ProfessorCod).FirstOrDefault();
            
            if (existingProfessor == null)
            {
                try
                {
                    sistemaEvaluacionEntities.Professors.Add(professor);
                    sistemaEvaluacionEntities.SaveChanges();
                }
                catch (Exception ex)
                {
                    return ex.ToString();
                }
            }
            else
            {
                return "El código del profesor ya está en uso";
            }
            
            return "Datos Guardados";
        }

        [HttpGet]
        public JsonResult GetAllProfessors()
        {
            List<Professors> professorsList = sistemaEvaluacionEntities.Professors.Where(s => s.Status == 1 && s.Assigned != true).ToList();

            var subCategoryToReturn = professorsList.Select(s => new Professors
            {
                ID              = s.ID,
                Name            = s.Name,
                LastName        = s.LastName,
                DateOfBirth     = s.DateOfBirth,
                Identification  = s.Identification,
                TelephoneNumber = s.TelephoneNumber,
                CellPhoneNumber = s.CellPhoneNumber,
                Gender          = s.Gender,
                Address         = s.Address,
                City            = s.City,
                CountryOfBirth  = s.CountryOfBirth,
                Photo           = s.Photo,
                ProfessorCod    = s.ProfessorCod,
                Password        = s.Password,
            });

            if (subCategoryToReturn == null)
            {
                return new JsonResult { Data = "No hay profesores registrados", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }

            return new JsonResult { Data = subCategoryToReturn, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult EditProfessor(Professors professor)
        {
            if (professor != null)
            {
                var currentProfessor = sistemaEvaluacionEntities.Professors.Where(a => a.ID == professor.ID).FirstOrDefault();

                currentProfessor.Name            = professor.Name;
                currentProfessor.LastName        = professor.LastName;
                currentProfessor.DateOfBirth     = professor.DateOfBirth;
                currentProfessor.Identification  = professor.Identification;
                currentProfessor.TelephoneNumber = professor.TelephoneNumber;
                currentProfessor.CellPhoneNumber = professor.CellPhoneNumber;
                currentProfessor.Gender          = professor.Gender;
                currentProfessor.Address         = professor.Address;
                currentProfessor.City            = professor.City;
                currentProfessor.CountryOfBirth  = professor.CountryOfBirth;
                currentProfessor.Photo           = professor.Photo;
                currentProfessor.ProfessorCod    = professor.ProfessorCod;
                currentProfessor.Password        = professor.TelephoneNumber;
                currentProfessor.UpdatedBy       = Convert.ToInt32(Session["CodUser"]);

                try
                {
                    sistemaEvaluacionEntities.SaveChanges();
                }
                catch
                {
                    return Json(new { message = "Error", status = "Ha Ocurrido un Error al Actualizar el Profesor" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { message = "Éxito", status = "Profesor Modificado Correctamente" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteProfessor(int professorId)
        {
            var currentProfessor = sistemaEvaluacionEntities.Professors.Where(a => a.ID == professorId).FirstOrDefault();

            if (currentProfessor != null)
            {
                try
                {
                    currentProfessor.Status = 0;

                    sistemaEvaluacionEntities.Entry(currentProfessor).State = EntityState.Modified;
                    sistemaEvaluacionEntities.SaveChanges();
                }
                catch
                {
                    return Json(new { message = "Error", status = "Hubo un Error al Eliminar el Profesor" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { message = "Éxito", status = "Profesor Eliminado con Éxito" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public void UpdateAssignedProfessorFlag(int professorId)
        {
            var professor = sistemaEvaluacionEntities.Professors.Where(p => p.ProfessorCod == professorId).FirstOrDefault();

            professor.Assigned = true;

            sistemaEvaluacionEntities.SaveChanges();
        }

        public int RandomNumber()
        {
            var randomNumber = util.GenerateRandomNumber();
            return randomNumber;
        }

    }
}

Sistema_Evaluacion/Sistema_Evaluacion/Views/Professor/Create.cshtml
@{
    ViewBag.Title = "Nuevo Docente";
}

<!-- Single pro tab review Start-->
<div ng-controller="ProfessorCreateController" class="single-pro-review-area mt-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-payment-inner-st">
                    <ul id="myTabedu1" class="tab-review-design">
                        <li class="active"><a href="#description">Información Básica</a></li>
                        <li><a href="#reviews">Información de la Cuenta</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content custom-product-edit">
                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="review-content-section">
                                        <div id="dropzone1" class="pro-ad">
                                            <form action="/upload" class="dropzone dropzone-custom needsclick add-professors" id="demo1-upload">
                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Nombre" ng-model="professorName">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Apellido" ng-model="professorLastName">
                                                        </div>
                                                        <div class="form-group">
                                                            <input id="finish" type="text" class="form-control" placeholder="Fecha de Nacimiento" ng-model="professorDateOfBirth">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="number" class="form-control" placeholder="Cédula" ng-model="professorIdentification">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="number" class="form-control" placeholder="Número de contacto" ng-model="professorContactNumber">
                                                        </div>                                                    
                                                        <div class="form-group alert-up-pd">
                                                            <div class="dz-message needsclick download-custom">
                                                                <i class="fa fa-download edudropnone" aria-hidden="true"></i>
                                                                <h2 class="edudropnone">Drop image here or click to upload.</h2>
                                                                <p class="edudropnone">
                                                                    <span class="note needsclick">(This is just a demo dropzone. Selected image is <strong>not</strong> actually uploaded.)</span>
                                                                </p>
                                                                <input name="imageico" class="hd-pro-img" type="text" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Asignatura" ng-model="professorSubject">
                                                        </div>
                                                        <div class="form-group res-mg-t-15">
                                                            <textarea placeholder="Dirección de domicilio" ng-model="professorAddress"></textarea>
                                                        </div>
                                                        
                                                        
                                                    </div>
                                                </div>
                                                @*<div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="payment-adress">
                                                            <a href="#reviews" >Siguiente</a>
                                                        </div>
                                                    </div>
                                                </div>*@
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-tab-list tab-pane fade" id="reviews">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <form id="acount-infor" action="#" class="acount-infor">
                                                    <div class="devit-card-custom">
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" disabled placeholder="Código" id="professorCode" ng-model="professorCod">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="password" class="form-control" placeholder="Contraseña" ng-model="professorPassword">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="password" class="form-control" placeholder="Confirmar Contraseña">
                                                        </div>
                                                        <a ng-click="createProfessor()" class="btn btn-primary waves-effect waves-light">Guardar</a>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Sistema_Evaluacion/Sistema_Evaluacion/Views/Professor/ViewAll.cshtml
@{
    ViewBag.Title = "Listado de Docentes";
}

    <style>
        .newProfessorInput {
            font-weight: bold;
            font-family: inherit;
            font-size: 100%;
            line-height: 3.15;
            margin-left: 1520px;
        }
    </style>

<!-- Static Table Start -->
<div ng-controller="ViewAllProfessorController" class="static-table-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="sparkline8-list">
                    <div class="sparkline8-hd">
                        <div class="main-sparkline8-hd">
                            <h1>Docentes</h1>
                        </div>
                    </div>
                    <div class="sparkline8-graph">
                        <div class="static-table-list">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Código</th>
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th>Asignatura</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr style="color:blue;" ng-repeat="professor in professors" ng-click="getProfessorInformationModal(professor);openProfessorModifyModal()">
                                        <td>{{professor.ProfessorCod}}</td>
                                        <td>{{professor.Name}}</td>
                                        <td>{{professor.LastName}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <br />
                    <input class="btn-primary newProfessorInput" type="button" value="Nuevo Docente" onclick='window.location = "@Url.Action("Create", "Professor")";' />
                </div>
            </div>
        </div>
    </div>
    <!-- Static Table End -->

    <!-- Edit Modal -->
    <div class="modal fade" id="professorModifyModal" tabindex="-1" data-toggle="modal" data-backdrop="static" data-keyboard="false" role="dialog" aria-labelledby="modifyModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Editar Docente</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body row">
                    <div class="col-lg-6">
                        <label>Nombre</label>
                        <input type="text" class="form-control" ng-model="professorInformationModal.Name" />
                    </div>

                    <div class="col-lg-6">
                        <label>Apellido</label>
                        <input class="form-control" ng-model="professorInformationModal.LastName" />
                    </div>

                    <div class="col-lg-6">
                        <label>Fecha de Nacimiento</label>
                        <input class="form-control" ng-model="professorInformationModal.DateOfBirth" />
                    </div>

                    <div class="col-lg-6">
                        <label>Cédula</label>
                        <input class="form-control" ng-model="professorInformationModal.Identification" />
                    </div>

                    <div class="col-lg-6">
                        <label>Número de Teléfono</label>
                        <input type="text" class="form-control" ng-model="professorInformationModal.TelephoneNumber" />
                    </div>

                    <div class="col-lg-6">
                        <label>Número de Celular</label>
                        <input type="text" class="form-control" ng-model="professorInformationModal.CellPhoneNumber" />
                    </div>

                    <div class="col-lg-6">
                        <label>Género</label>
                        <input type="text" class="form-control" ng-model="professorInformationModal.Gender" />
                    </div>

                    <div class="col-lg-6">
                        <label>Asignatura</label>
                        <input type="text" class="form-control" ng-model="professorInformationModal.Subject" />
                    </div>

                    <div class="col-lg-6">
                        <label>Ciudad</label>
                        <input type="text" class="form-control" ng-model="professorInformationModal.City" />
                    </div>

                    <div class="col-lg-6">
                        <label>País de Nacimiento</label>
                        <input type="text" class="form-control" ng-model="professorInformationModal.CountryOfBirth" />
                    </div>

                    <div class="col-lg-6">
                        <label>Código</label>
                        <input type="text" class="form-control" disabled ng-model="professorInformationModal.ProfessorCod" />
                    </div>

                    <div class="col-lg-6">
                        <label>Contraseña</label>
                        <input type="text" class="form-control" ng-model="professorInformationModal.Password" />
                    </div>

                    <div class="form-group col-md-12">
                        <label>Dirección</label>
                        <textarea class="form-control" style="resize: none;" ng-model="professorInformationModal.Address" rows="4"></textarea>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" ng-click="editProfessor(professorInformationModal)">Modificar</button>
                    <button type="button" class="btn btn-danger" ng-click="changeProfessorStatus(professorInformationModal.ID)">Desactivar Docente</button>
                    <button type="button" class="btn btn-danger" ng-click="deleteProfessor(professorInformationModal.ID)">Eliminar</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Edit Modal -->
</div>